version: "3.2"

services:

  rabbit_mq:

    image: rabbitmq:3.8-rc-management
    container_name: rabbit_mq
    ports:
        - 5672:5672
        - 15672:15672

  producer:
    build: producer
    depends_on:
        - rabbit_mq
    ports:
        - 8000:8000
    environment:
        RABBITMQ: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./producer:/Users/vaibhav/Desktop/cchackathon/producer

  consumer1:
    build: consumer
    depends_on:
        - rabbit_mq
        - producer
    environment:
        RABBITMQ: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
        CID: 'c1'
        SERVER_URL: 'http://producer:8000/new_ride_matching_consumer'
    volumes:
      - ./consumer:/Users/vaibhav/Desktop/cchackathon/consumer

  consumer2:
    build: consumer
    depends_on:
        - rabbit_mq
        - producer
    environment:
        RABBITMQ: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
        CID: 'c2'
        SERVER_URL: 'http://producer:8000/new_ride_matching_consumer'
    volumes:
      - ./consumer:/Users/vaibhav/Desktop/cchackathon/consumer

  database:
    build: database
    depends_on:
        - rabbit_mq
        - producer
    environment:
        RABBITMQ: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./database:/Users/vaibhav/Desktop/cchackathon/database

volumes:
    rabbit_mqdata:
      driver: local